/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ContactChangesRouteImport } from './routes/contact-changes'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as MeRouteImport } from './routes/me'
import { Route as MeAbsencesRouteImport } from './routes/me-absences'
import { Route as MePayrollRouteImport } from './routes/me-payroll'
import { Route as MeProfileRouteImport } from './routes/me-profile'
import { Route as MeRequestsRouteImport } from './routes/me-requests'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as ResignationsRouteImport } from './routes/resignations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactChangesRoute = ContactChangesRouteImport.update({
  id: '/contact-changes',
  path: '/contact-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MeAbsencesRoute = MeAbsencesRouteImport.update({
  id: '/me-absences',
  path: '/me-absences',
  getParentRoute: () => rootRouteImport,
} as any)
const MePayrollRoute = MePayrollRouteImport.update({
  id: '/me-payroll',
  path: '/me-payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me-profile',
  path: '/me-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRequestsRoute = MeRequestsRouteImport.update({
  id: '/me-requests',
  path: '/me-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const ResignationsRoute = ResignationsRouteImport.update({
  id: '/resignations',
  path: '/resignations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact-changes': typeof ContactChangesRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/invoices': typeof InvoicesRoute
  '/journal': typeof JournalRoute
  '/leaves': typeof LeavesRoute
  '/me': typeof MeRoute
  '/me-absences': typeof MeAbsencesRoute
  '/me-payroll': typeof MePayrollRoute
  '/me-profile': typeof MeProfileRoute
  '/me-requests': typeof MeRequestsRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/recruitment': typeof RecruitmentRoute
  '/resignations': typeof ResignationsRoute
  '/settings': typeof SettingsRoute
  '/tax': typeof TaxRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact-changes': typeof ContactChangesRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/invoices': typeof InvoicesRoute
  '/journal': typeof JournalRoute
  '/leaves': typeof LeavesRoute
  '/me': typeof MeRoute
  '/me-absences': typeof MeAbsencesRoute
  '/me-payroll': typeof MePayrollRoute
  '/me-profile': typeof MeProfileRoute
  '/me-requests': typeof MeRequestsRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/recruitment': typeof RecruitmentRoute
  '/resignations': typeof ResignationsRoute
  '/settings': typeof SettingsRoute
  '/tax': typeof TaxRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact-changes': typeof ContactChangesRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/invoices': typeof InvoicesRoute
  '/journal': typeof JournalRoute
  '/leaves': typeof LeavesRoute
  '/me': typeof MeRoute
  '/me-absences': typeof MeAbsencesRoute
  '/me-payroll': typeof MePayrollRoute
  '/me-profile': typeof MeProfileRoute
  '/me-requests': typeof MeRequestsRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/recruitment': typeof RecruitmentRoute
  '/resignations': typeof ResignationsRoute
  '/settings': typeof SettingsRoute
  '/tax': typeof TaxRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/audit'
    | '/auth'
    | '/branches'
    | '/careers'
    | '/company'
    | '/contact-changes'
    | '/contracts'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/expenses'
    | '/income'
    | '/invoices'
    | '/journal'
    | '/leaves'
    | '/me'
    | '/me-absences'
    | '/me-payroll'
    | '/me-profile'
    | '/me-requests'
    | '/payments'
    | '/payroll'
    | '/profile'
    | '/recruitment'
    | '/resignations'
    | '/settings'
    | '/tax'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/audit'
    | '/auth'
    | '/branches'
    | '/careers'
    | '/company'
    | '/contact-changes'
    | '/contracts'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/expenses'
    | '/income'
    | '/invoices'
    | '/journal'
    | '/leaves'
    | '/me'
    | '/me-absences'
    | '/me-payroll'
    | '/me-profile'
    | '/me-requests'
    | '/payments'
    | '/payroll'
    | '/profile'
    | '/recruitment'
    | '/resignations'
    | '/settings'
    | '/tax'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/audit'
    | '/auth'
    | '/branches'
    | '/careers'
    | '/company'
    | '/contact-changes'
    | '/contracts'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/expenses'
    | '/income'
    | '/invoices'
    | '/journal'
    | '/leaves'
    | '/me'
    | '/me-absences'
    | '/me-payroll'
    | '/me-profile'
    | '/me-requests'
    | '/payments'
    | '/payroll'
    | '/profile'
    | '/recruitment'
    | '/resignations'
    | '/settings'
    | '/tax'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  BranchesRoute: typeof BranchesRoute
  CareersRoute: typeof CareersRoute
  CompanyRoute: typeof CompanyRoute
  ContactChangesRoute: typeof ContactChangesRoute
  ContractsRoute: typeof ContractsRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  EmployeesRoute: typeof EmployeesRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomeRoute: typeof IncomeRoute
  InvoicesRoute: typeof InvoicesRoute
  JournalRoute: typeof JournalRoute
  LeavesRoute: typeof LeavesRoute
  MeRoute: typeof MeRoute
  MeAbsencesRoute: typeof MeAbsencesRoute
  MePayrollRoute: typeof MePayrollRoute
  MeProfileRoute: typeof MeProfileRoute
  MeRequestsRoute: typeof MeRequestsRoute
  PaymentsRoute: typeof PaymentsRoute
  PayrollRoute: typeof PayrollRoute
  ProfileRoute: typeof ProfileRoute
  RecruitmentRoute: typeof RecruitmentRoute
  ResignationsRoute: typeof ResignationsRoute
  SettingsRoute: typeof SettingsRoute
  TaxRoute: typeof TaxRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-changes': {
      id: '/contact-changes'
      path: '/contact-changes'
      fullPath: '/contact-changes'
      preLoaderRoute: typeof ContactChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me-absences': {
      id: '/me-absences'
      path: '/me-absences'
      fullPath: '/me-absences'
      preLoaderRoute: typeof MeAbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me-payroll': {
      id: '/me-payroll'
      path: '/me-payroll'
      fullPath: '/me-payroll'
      preLoaderRoute: typeof MePayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me-profile': {
      id: '/me-profile'
      path: '/me-profile'
      fullPath: '/me-profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me-requests': {
      id: '/me-requests'
      path: '/me-requests'
      fullPath: '/me-requests'
      preLoaderRoute: typeof MeRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resignations': {
      id: '/resignations'
      path: '/resignations'
      fullPath: '/resignations'
      preLoaderRoute: typeof ResignationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  BranchesRoute: BranchesRoute,
  CareersRoute: CareersRoute,
  CompanyRoute: CompanyRoute,
  ContactChangesRoute: ContactChangesRoute,
  ContractsRoute: ContractsRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  EmployeesRoute: EmployeesRoute,
  ExpensesRoute: ExpensesRoute,
  IncomeRoute: IncomeRoute,
  InvoicesRoute: InvoicesRoute,
  JournalRoute: JournalRoute,
  LeavesRoute: LeavesRoute,
  MeRoute: MeRoute,
  MeAbsencesRoute: MeAbsencesRoute,
  MePayrollRoute: MePayrollRoute,
  MeProfileRoute: MeProfileRoute,
  MeRequestsRoute: MeRequestsRoute,
  PaymentsRoute: PaymentsRoute,
  PayrollRoute: PayrollRoute,
  ProfileRoute: ProfileRoute,
  RecruitmentRoute: RecruitmentRoute,
  ResignationsRoute: ResignationsRoute,
  SettingsRoute: SettingsRoute,
  TaxRoute: TaxRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
